from mock import patch

from crawler.pages.wizards import WizardsHomePage
from crawler.tests.helpers import get_html_fixture
from crawler.tests.pages.base import ProviderTest


class WizardsComParsingTest(ProviderTest):

    @patch.object(WizardsHomePage, 'get_content')
    def test_wizards_products_list(self, get_content):
        get_content.return_value = get_html_fixture('wizards_products')
        p = WizardsHomePage()
        products = p.products_list()
        self.assertEqual(products, [
            ('Magic 2013', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/magic2013', {'release': 'July 2012', 'cards': 249}),
            ('Avacyn Restored', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/avacynrestored/productinfo', {'release': 'May 2012', 'cards': 244}),
            ('Dark Ascension', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/darkascension/productinfo', {'release': 'February 2012', 'cards': 158}),
            ('Innistrad', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/innistrad', {'release': 'September 2011', 'cards': 264}),
            ('Magic 2012', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/magic2012', {'release': 'July 2011', 'cards': 249}),
            ('New Phyrexia', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/newphyrexia/productinfo', {'release': 'May 2011', 'cards': 175}),
            ('Mirrodin Besieged', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/mirrodinbesieged', {'release': 'February 2011', 'cards': 155}),
            ('Scars of Mirrodin', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/scarsofmirrodin', {'release': 'October 2010', 'cards': 249}),
            ('Magic 2011', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/magic2011', {'release': 'July 2010', 'cards': 249}),
            ('Rise of the Eldrazi', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/riseoftheeldrazi', {'release': 'April 2010', 'cards': 248}),
            ('Worldwake', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/worldwake', {'release': 'February 2010', 'cards': 145}),
            ('Zendikar', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/zendikar', {'release': 'October 2009', 'cards': 249}),
            ('Magic 2010', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/magic2010', {'release': 'July 2009', 'cards': 249}),
            ('Alara Reborn', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/alarareborn', {'release': 'April 2009', 'cards': 145}),
            ('Conflux', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/conflux', {'release': 'February 2009', 'cards': 145}),
            ('Shards of Alara', u'http://wizards.com/magic/tcg/products.aspx?x=mtg/tcg/products/shardsofalara', {'release': 'October 2008', 'cards': 249}),
            ('Eventide', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/eventide/productinfo', {'release': 'July 2008', 'cards': 180}),
            ('Shadowmoor', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/shadowmoor/productinfo', {'release': 'May 2008', 'cards': 301}),
            ('Morningtide', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/morningtide/productinfo', {'release': 'February 2008', 'cards': 150}),
            ('Lorwyn', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/lorwyn/productinfo', {'release': 'October 2007', 'cards': 301}),
            ('Tenth Edition', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/tenth/productinfo', {'release': 'July 2007', 'cards': 383}),
            ('Future Sight', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/futuresight/productinfo', {'release': 'May 2007', 'cards': 180}),
            ('Planar Chaos', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/planarchaos/productinfo', {'release': 'February 2007', 'cards': 165}),
            ('Time Spiral', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/timespiral/productinfo', {'release': 'October 2006', 'cards': 422}),
            ('Coldsnap', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/coldsnap/productinfo', {'release': 'July 2006', 'cards': 155}),
            ('Dissension', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/dissension/productinfo', {'release': 'May 2006', 'cards': 180}),
            ('Guildpact', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/guildpact/productinfo', {'release': 'February 2006', 'cards': 165}),
            ('Ravnica: City of Guilds', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/ravnica/productinfo', {'release': 'October 2005', 'cards': 306}),
            ('Ninth Edition', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/ninth/productinfo', {'release': 'July 2005', 'cards': 359}),
            ('Saviors of Kamigawa', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/saviorsofkamigawa/productinfo', {'release': 'June 2005', 'cards': 165}),
            ('Betrayers of Kamigawa', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/betrayersofkamigawa/productinfo', {'release': 'February 2005', 'cards': 165}),
            ('Champions of Kamigawa', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/championsofkamigawa/productinfo', {'release': 'October 2004', 'cards': 306}),
            ('Fifth Dawn', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/fifthdawn/productinfo', {'release': 'June 2004', 'cards': 165}),
            ('Darksteel', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/darksteel/productinfo', {'release': 'February 2004', 'cards': 165}),
            ('Mirrodin', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/mirrodin/productinfo', {'release': 'October 2003', 'cards': 306}),
            ('Eighth Edition', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/eighth/productinfo', {'release': 'July 2003', 'cards': 357}),
            ('Scourge', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/scourge/productinfo', {'release': 'May 2003', 'cards': 143}),
            ('Legions', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/legions/productinfo', {'release': 'February 2003', 'cards': 145}),
            ('Onslaught', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/onslaught/productinfo', {'release': 'October 2002', 'cards': 350}),
            ('Judgment', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/judgment/productinfo', {'release': 'May 2002', 'cards': 143}),
            ('Torment', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/torment/productinfo', {'release': 'February 2002', 'cards': 143}),
            ('Odyssey', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/odyssey/productinfo', {'release': 'October 2001', 'cards': 350}),
            ('Apocalypse', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/apocalypse/productinfo', {'release': 'June 2001', 'cards': 143}),
            ('Seventh Edition', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/seventh/productinfo', {'release': 'April 2001', 'cards': 350}),
            ('Planeshift', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/planeshift/productinfo', {'release': 'February 2001', 'cards': 143}),
            ('Invasion', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/invasion/productinfo', {'release': 'October 2000', 'cards': 350}),
            ('Prophecy', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/prophecy/productinfo', {'release': 'June 2000', 'cards': 143}),
            ('Nemesis', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/nemesis/productinfo', {'release': 'February 2000', 'cards': 143}),
            ('Mercadian Masques', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/mercadianmasques/productinfo', {'release': 'October 1999', 'cards': 350}),
            ("Urza's Destiny", u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/urzasdestiny/productinfo', {'release': 'June 1999', 'cards': 143}),
            ('Classic Sixth Edition', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/sixth/productinfo', {'release': 'April 1999', 'cards': 350}),
            ("Urza's Legacy", u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/urzaslegacy/productinfo', {'release': 'February 1999', 'cards': 143}),
            ("Urza's Saga", u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/urzassaga/productinfo', {'release': 'October 1998', 'cards': 350}),
            ('Exodus', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/exodus/productinfo', {'release': 'June 1998', 'cards': 143}),
            ('Stronghold', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/stronghold/productinfo', {'release': 'March 1998', 'cards': 143}),
            ('Tempest', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/tempest/productinfo', {'release': 'October 1997', 'cards': 350}),
            ('Weatherlight', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/weatherlight/productinfo', {'release': 'June 1997', 'cards': 167}),
            ('Fifth Edition', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/fifth/productinfo', {'release': 'March 1997', 'cards': 449}),
            ('Visions', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/visions/productinfo', {'release': 'February 1997', 'cards': 167}),
            ('Mirage', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/mirage/productinfo', {'release': 'October 1996', 'cards': 350}),
            ('Alliances', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/alliances/productinfo', {'release': 'June 1996', 'cards': 143}),
            ('Homelands', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/homelands/productinfo', {'release': 'October 1995', 'cards': 115}),
            ('Ice Age', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/iceage/productinfo', {'release': 'June 1995', 'cards': 383}),
            ('Fourth Edition', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/fourth/productinfo', {'release': 'April 1995', 'cards': 378}),
            ('Fallen Empires', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/fallenempires/productinfo', {'release': 'November 1994', 'cards': 102}),
            ('The Dark', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/thedark/productinfo', {'release': 'August 1994', 'cards': 119}),
            ('Legends', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/legends/productinfo', {'release': 'June 1994', 'cards': 310}),
            ('Revised', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/revised/productinfo', {'release': 'April 1994', 'cards': 306}),
            ('Antiquities', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/antiquities/productinfo', {'release': 'March 1994', 'cards': 100}),
            ('Arabian Nights', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/arabiannights/productinfo', {'release': 'December 1993', 'cards': 92}),
            ('Alpha', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/abu/productinfo', {'release': 'August 1993', 'cards': 295}),
            ('Beta', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/abu/productinfo', {'release': 'August 1993', 'cards': 295}),
            ('Unlimited', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/abu/productinfo', {'release': 'August 1993', 'cards': 295}),
            ('Venser vs. Koth', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/venservskoth/productinfo', {'release': 'March 2012', 'cards': None}),
            ('Ajani vs. Nicol Bolas', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/ajanivsnicolbolas/productinfo', {'release': 'September 2011', 'cards': None}),
            ('Knights vs. Dragons', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/knightsvsdragons/productinfo', {'release': 'April 2011', 'cards': None}),
            ('Elspeth vs. Tezzeret', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/elspethvstezzeret/productinfo', {'release': 'September 2010', 'cards': None}),
            ('Phyrexia vs. the Coalition', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/phyrexiavsthecoalition/productinfo', {'release': 'March 2010', 'cards': None}),
            ('Garruk vs. Liliana', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/garrukvsliliana/productinfo', {'release': 'November 2009', 'cards': None}),
            ('Divine vs. Demonic', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/divinevsdemonic/productinfo', {'release': 'April 2009', 'cards': None}),
            ('Jace vs. Chandra', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/jacevschandra/productinfo', {'release': 'November 2008', 'cards': None}),
            ('Elves vs. Goblins', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/elvesvsgoblins/productinfo', {'release': 'November 2007', 'cards': None}),
            ('Masters Edition IV', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/mastersed4/productinfo', {'release': 'January 2011', 'cards': 245}),
            ('Masters Edition III', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/mastersed3/productinfo', {'release': 'September 2009', 'cards': 245}),
            ('Masters Edition II', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/mastersed2/productinfo', {'release': 'September 2008', 'cards': 245}),
            ('Masters Edition', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg_tcg_mastersed_productinfo', {'release': 'September 2007', 'cards': 195}),
            ('From the Vault: Realms', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/ftvrealms/productinfo', {'release': 'August 2012', 'cards': 15}),
            ('From the Vault: Legends', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/ftvlegends/productinfo', {'release': 'August 2011', 'cards': 15}),
            ('From the Vault: Relics', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/ftvrelics/productinfo', {'release': 'August 2010', 'cards': 15}),
            ('From the Vault: Exiled', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/ftvexiled/productinfo', {'release': 'August 2009', 'cards': 15}),
            ('From the Vault: Dragons', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg_tcg_dragons_productinfo', {'release': 'August 2008', 'cards': 15}),
            ('Legacy', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/mtgodeckseries/productinfo', {'release': 'November 2010', 'cards': None}),
            ('Momir Vig Basic', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/mtgomomirvig/productinfo', {'release': 'November 2010', 'cards': None}),
            ('Deckmasters 2001', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/deckmasters2001/productinfo', {'release': 'December 2001', 'cards': None}),
            ('Beatdown', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/beatdown/productinfo', {'release': 'October 2000', 'cards': None}),
            ('Battle Royale', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/battleroyale/productinfo', {'release': 'November 1999', 'cards': None}),
            ('Unhinged', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/unhinged/productinfo', {'release': 'November 2004', 'cards': 141}),
            ('Unglued', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/unglued/productinfo', {'release': 'August 1998', 'cards': 88}),
            ('Premium Foil Booster', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/premiumfoilbooster/productinfo', {'release': 'January 2010', 'cards': None}),
            ('Anthologies', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/anthologies/productinfo', {'release': 'November 1998', 'cards': None}),
            ('Chronicles / Renaissance', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/chronren/productinfo', {'release': 'July 1995', 'cards': 116}),
            ('Starter 2000', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/starter/productinfo', {'release': 'July 2000', 'cards': 173}),
            ('Starter 1999', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/starter99/productinfo', {'release': 'July 1999', 'cards': 173}),
            ('Portal Three Kingdoms', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/portalthree/productinfo', {'release': 'May 1999', 'cards': 180}),
            ('Portal Second Age', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/portal/productinfo', {'release': 'June 1998', 'cards': 215}),
            ('Portal', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/portal/productinfo', {'release': 'June 1997', 'cards': 215}),
            ('Planechase (2012 Edition)', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/planechase2012edition/productinfo', {'release': 'June 2012', 'cards': None}),
            ('Magic: The Gathering Commander', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/commander/productinfo', {'release': 'June 2011', 'cards': None}),
            ('Archenemy', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/archenemy/productinfo', {'release': 'June 2010', 'cards': None}),
            ('Planechase', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/planechase/productinfo', {'release': 'September 2009', 'cards': None}),
            ('Vanguard', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/vanguard/productinfo', {'release': 'July 1997', 'cards': None}),
            ('Premium Deck Series: Graveborn', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/pdsgraveborn/productinfo', {'release': 'November 2011', 'cards': None}),
            ('Premium Deck Series: Fire & Lightning', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/pdsfirelightning/productinfo', {'release': 'November 2010', 'cards': None}),
            ('Premium Deck Series: Slivers', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/pdsslivers/productinfo', {'release': 'November 2009', 'cards': None}),
            ('Duels of the Planeswalkers Decks', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/dotpdecks/productinfo', {'release': 'June 2010', 'cards': None}),
            ("Deck Builder's Toolkit", u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/dbt/productinfo', {'release': 'May 2010', 'cards': None}),
            ('World Champ Decks 2004', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/champdeck2004/productinfo', {'release': '2004', 'cards': None}),
            ('World Champ Decks 2003', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/champdeck2003/productinfo', {'release': '2003', 'cards': None}),
            ('World Champ Decks 2002', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/champdeck2002/productinfo', {'release': '2002', 'cards': None}),
            ('World Champ Decks 2001', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/champdeck2001/productinfo', {'release': '2001', 'cards': None}),
            ('World Champ Decks 2000', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/champdeck2000/productinfo', {'release': '2000', 'cards': None}),
            ('World Champ Decks 1999', u'http://wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/champdeck1999/productinfo', {'release': '1999', 'cards': None}),
        ])
