import os
from settings.common import *

ALLOWED_HOSTS = ['127.0.0.1']

# Get application version. It is generated by fabric while deploy
try:
    with open('/etc/mtgforge/version') as f:
        version = f.read().strip()
except IOError:
    version = None

# Absolute filesystem path to the directory that will hold user-uploaded files.
MEDIA_ROOT = '/var/www/mtgforge-media/'

# Absolute path to the directory static files should be collected to.
# Don't put anything in this directory yourself; store your static files
# in apps' "static/" subdirectories and in STATICFILES_DIRS.
STATIC_ROOT = '/var/www/mtgforge-static/'

# Add suffix for application statatic base dir to prevent browser caching
if version is not None:
    STATIC_ROOT = os.path.join(STATIC_ROOT, version)
    STATIC_URL = STATIC_URL + version + '/'


ADMINS = (
    ('Anton Egorov', 'anton.egoroff@gmail.com'),
)

MANAGERS = ADMINS

try:
    from settings.local import *
except ImportError:
    pass
