MEDIA_BUNDLES = (
    ( 'libs.css',
        'bootstrap/css/bootstrap.css',
    ),
    ( 'common.css',
        'css/icons.sass',
        'css/sprites.css',
        'css/main.sass',
        'css/search.sass',
        'css/cards.sass',
    ),
    ( 'libs.js',
        'js/lib/jquery.js',
        'js/lib/jquery.unserialize.js',
        'bootstrap/js/bootstrap.js',
        'js/lib/underscore.js',
        'js/lib/backbone.js',
        'js/lib/backbone.meta.js',
    ),
    ( 'common.js',
        'js/app.coffee',
    ),
    ( 'models.js',
        'js/models/card.coffee',
        'js/models/search.coffee',
    ),
    ( 'collections.js',
        'js/collections/cards.coffee'
    ),
    ( 'views.js',
        'js/views/app.coffee',
        'js/views/index.coffee',
        'js/views/search.coffee',
        'js/views/cards.coffee',
    ),
    ( 'router.js',
        'js/router.coffee',
    ),
    ( 'templates.js',
        'templates/cards.jst',
        'templates/index.jst',
        'templates/search/simple.jst',
        'templates/search/advanced.jst',
    ),
)
