MEDIA_BUNDLES = (
    ( 'libs.css',
        'bootstrap/css/bootstrap.css',
        'css/token-input.css',
        'css/token-input-facebook.css',
    ),
    ( 'common.css',
        'css/icons.sass',
        'css/sprites.css',
        'css/main.sass',
        'css/search.sass',
        'css/cards.sass',
    ),
    ( 'libs.js',
        'js/lib/jquery.js',
        'js/lib/jquery.unserialize.js',
        'js/lib/jquery.tokeninput.js',
        'bootstrap/js/bootstrap.js',
        'js/lib/batman.js',
        'js/lib/batman.jquery.js',
    ),
    ( 'common.js',
        'js/app.coffee',
    ),
    ( 'models.js',
        'js/models/card.coffee',
    ),
    ( 'controllers.js',
        'js/controllers/cards.coffee',
        'js/controllers/index.coffee',
        'js/controllers/search.coffee',
    ),
    ( 'views.js',
        'js/views/search.coffee'
    ),
    ( 'router.js',
    ),
    ( 'templates.js',
    ),
)
