MEDIA_BUNDLES = (
    ( 'libs.css',
        'bootstrap/css/bootstrap.css',
    ),
    ( 'common.css',
        'css/icons.sass',
        'css/main.sass',
        'css/search.sass',
    ),
    ( 'libs.js',
        'js/lib/jquery.js',
        'bootstrap/js/bootstrap.js',
        'js/lib/underscore.js',
        'js/lib/backbone.js',
    ),
    ( 'common.js',
        'js/app.coffee',
    ),
    ( 'models.js',
        'js/models/card.coffee',
    ),
    ( 'collections.js',
        'js/collections/cards.coffee'
    ),
    ( 'views.js',
        'js/views/cards.coffee',
    ),
    ( 'templates.jst',
        'templates/app.jst'
    ),
)
