from mock import patch

from oracle.providers.magiccards import MagiccardsHomePage
from oracle.tests.helpers import get_html_fixture
from oracle.tests.providers.base import ProviderTest


class MagiccardsInfoParsingTest(ProviderTest):

    @patch.object(MagiccardsHomePage, 'get_content')
    def test_magiccards_list(self, get_content):
        get_content.return_value = get_html_fixture('magiccards_products')
        p = MagiccardsHomePage()
        products = p.products_list()
        self.assertEqual(products, [
            ('Avacyn Restored', u'http://magiccards.info/avr/en.html', {'acronym': 'avr'}),
            ('Dark Ascension', u'http://magiccards.info/dka/en.html', {'acronym': 'dka'}),
            ('Innistrad', u'http://magiccards.info/isd/en.html', {'acronym': 'isd'}),
            ('New Phyrexia', u'http://magiccards.info/nph/en.html', {'acronym': 'nph'}),
            ('Mirrodin Besieged', u'http://magiccards.info/mbs/en.html', {'acronym': 'mbs'}),
            ('Scars of Mirrodin', u'http://magiccards.info/som/en.html', {'acronym': 'som'}),
            ('Rise of the Eldrazi', u'http://magiccards.info/roe/en.html', {'acronym': 'roe'}),
            ('Worldwake', u'http://magiccards.info/wwk/en.html', {'acronym': 'wwk'}),
            ('Zendikar', u'http://magiccards.info/zen/en.html', {'acronym': 'zen'}),
            ('Alara Reborn', u'http://magiccards.info/arb/en.html', {'acronym': 'arb'}),
            ('Conflux', u'http://magiccards.info/cfx/en.html', {'acronym': 'cfx'}),
            ('Shards of Alara', u'http://magiccards.info/ala/en.html', {'acronym': 'ala'}),
            ('Eventide', u'http://magiccards.info/eve/en.html', {'acronym': 'eve'}),
            ('Shadowmoor', u'http://magiccards.info/shm/en.html', {'acronym': 'shm'}),
            ('Morningtide', u'http://magiccards.info/mt/en.html', {'acronym': 'mt'}),
            ('Lorwyn', u'http://magiccards.info/lw/en.html', {'acronym': 'lw'}),
            ('Future Sight', u'http://magiccards.info/fut/en.html', {'acronym': 'fut'}),
            ('Planar Chaos', u'http://magiccards.info/pc/en.html', {'acronym': 'pc'}),
            ('Time Spiral', u'http://magiccards.info/ts/en.html', {'acronym': 'ts'}),
            ('Time Spiral "Timeshifted"', u'http://magiccards.info/tsts/en.html', {'acronym': 'tsts'}),
            ('Coldsnap', u'http://magiccards.info/cs/en.html', {'acronym': 'cs'}),
            ('Alliances', u'http://magiccards.info/ai/en.html', {'acronym': 'ai'}),
            ('Ice Age', u'http://magiccards.info/ia/en.html', {'acronym': 'ia'}),
            ('Dissension', u'http://magiccards.info/di/en.html', {'acronym': 'di'}),
            ('Guildpact', u'http://magiccards.info/gp/en.html', {'acronym': 'gp'}),
            ('Ravnica: City of Guilds', u'http://magiccards.info/rav/en.html', {'acronym': 'rav'}),
            ('Saviors of Kamigawa', u'http://magiccards.info/sok/en.html', {'acronym': 'sok'}),
            ('Betrayers of Kamigawa', u'http://magiccards.info/bok/en.html', {'acronym': 'bok'}),
            ('Champions of Kamigawa', u'http://magiccards.info/chk/en.html', {'acronym': 'chk'}),
            ('Fifth Dawn', u'http://magiccards.info/5dn/en.html', {'acronym': '5dn'}),
            ('Darksteel', u'http://magiccards.info/ds/en.html', {'acronym': 'ds'}),
            ('Mirrodin', u'http://magiccards.info/mi/en.html', {'acronym': 'mi'}),
            ('Scourge', u'http://magiccards.info/sc/en.html', {'acronym': 'sc'}),
            ('Legions', u'http://magiccards.info/le/en.html', {'acronym': 'le'}),
            ('Onslaught', u'http://magiccards.info/on/en.html', {'acronym': 'on'}),
            ('Judgment', u'http://magiccards.info/ju/en.html', {'acronym': 'ju'}),
            ('Torment', u'http://magiccards.info/tr/en.html', {'acronym': 'tr'}),
            ('Odyssey', u'http://magiccards.info/od/en.html', {'acronym': 'od'}),
            ('Apocalypse', u'http://magiccards.info/ap/en.html', {'acronym': 'ap'}),
            ('Planeshift', u'http://magiccards.info/ps/en.html', {'acronym': 'ps'}),
            ('Invasion', u'http://magiccards.info/in/en.html', {'acronym': 'in'}),
            ('Prophecy', u'http://magiccards.info/pr/en.html', {'acronym': 'pr'}),
            ('Nemesis', u'http://magiccards.info/ne/en.html', {'acronym': 'ne'}),
            ('Mercadian Masques', u'http://magiccards.info/mm/en.html', {'acronym': 'mm'}),
            ("Urza's Destiny", u'http://magiccards.info/ud/en.html', {'acronym': 'ud'}),
            ("Urza's Legacy", u'http://magiccards.info/ul/en.html', {'acronym': 'ul'}),
            ("Urza's Saga", u'http://magiccards.info/us/en.html', {'acronym': 'us'}),
            ('Exodus', u'http://magiccards.info/ex/en.html', {'acronym': 'ex'}),
            ('Stronghold', u'http://magiccards.info/sh/en.html', {'acronym': 'sh'}),
            ('Tempest', u'http://magiccards.info/tp/en.html', {'acronym': 'tp'}),
            ('Weatherlight', u'http://magiccards.info/wl/en.html', {'acronym': 'wl'}),
            ('Visions', u'http://magiccards.info/vi/en.html', {'acronym': 'vi'}),
            ('Mirage', u'http://magiccards.info/mr/en.html', {'acronym': 'mr'}),
            ('Homelands', u'http://magiccards.info/hl/en.html', {'acronym': 'hl'}),
            ('Fallen Empires', u'http://magiccards.info/fe/en.html', {'acronym': 'fe'}),
            ('The Dark', u'http://magiccards.info/dk/en.html', {'acronym': 'dk'}),
            ('Legends', u'http://magiccards.info/lg/en.html', {'acronym': 'lg'}),
            ('Antiquities', u'http://magiccards.info/aq/en.html', {'acronym': 'aq'}),
            ('Arabian Nights', u'http://magiccards.info/an/en.html', {'acronym': 'an'}),
            ('Magic 2013', u'http://magiccards.info/m13/en.html', {'acronym': 'm13'}),
            ('Magic 2012', u'http://magiccards.info/m12/en.html', {'acronym': 'm12'}),
            ('Magic 2011', u'http://magiccards.info/m11/en.html', {'acronym': 'm11'}),
            ('Magic 2010', u'http://magiccards.info/m10/en.html', {'acronym': 'm10'}),
            ('Tenth Edition', u'http://magiccards.info/10e/en.html', {'acronym': '10e'}),
            ('Ninth Edition', u'http://magiccards.info/9e/en.html', {'acronym': '9e'}),
            ('Eighth Edition', u'http://magiccards.info/8e/en.html', {'acronym': '8e'}),
            ('Seventh Edition', u'http://magiccards.info/7e/en.html', {'acronym': '7e'}),
            ('Classic Sixth Edition', u'http://magiccards.info/6e/en.html', {'acronym': '6e'}),
            ('Fifth Edition', u'http://magiccards.info/5e/en.html', {'acronym': '5e'}),
            ('Fourth Edition', u'http://magiccards.info/4e/en.html', {'acronym': '4e'}),
            ('Revised Edition', u'http://magiccards.info/rv/en.html', {'acronym': 'rv'}),
            ('Unlimited Edition', u'http://magiccards.info/un/en.html', {'acronym': 'un'}),
            ('Limited Edition Beta', u'http://magiccards.info/be/en.html', {'acronym': 'be'}),
            ('Limited Edition Alpha', u'http://magiccards.info/al/en.html', {'acronym': 'al'}),
            ('MTGO Masters Edition IV', u'http://magiccards.info/me4/en.html', {'acronym': 'me4'}),
            ('MTGO Masters Edition III', u'http://magiccards.info/me3/en.html', {'acronym': 'me3'}),
            ('MTGO Masters Edition II', u'http://magiccards.info/me2/en.html', {'acronym': 'me2'}),
            ('MTGO Masters Edition', u'http://magiccards.info/med/en.html', {'acronym': 'med'}),
            ('Premium Deck Series: Graveborn', u'http://magiccards.info/pd3/en.html', {'acronym': 'pd3'}),
            ('Premium Deck Series: Fire and Lightning', u'http://magiccards.info/pd2/en.html', {'acronym': 'pd2'}),
            ('Premium Deck Series: Slivers', u'http://magiccards.info/pds/en.html', {'acronym': 'pds'}),
            ('Duels of the Planeswalkers', u'http://magiccards.info/dpa/en.html', {'acronym': 'dpa'}),
            ('Chronicles', u'http://magiccards.info/ch/en.html', {'acronym': 'ch'}),
            ('Planechase 2012 Edition', u'http://magiccards.info/pc2/en.html', {'acronym': 'pc2'}),
            ('Commander', u'http://magiccards.info/cmd/en.html', {'acronym': 'cmd'}),
            ('Archenemy', u'http://magiccards.info/arc/en.html', {'acronym': 'arc'}),
            ('Planechase', u'http://magiccards.info/pch/en.html', {'acronym': 'pch'}),
            ('From the Vault: Legends', u'http://magiccards.info/fvl/en.html', {'acronym': 'fvl'}),
            ('From the Vault: Relics', u'http://magiccards.info/fvr/en.html', {'acronym': 'fvr'}),
            ('From the Vault: Exiled', u'http://magiccards.info/fve/en.html', {'acronym': 'fve'}),
            ('From the Vault: Dragons', u'http://magiccards.info/fvd/en.html', {'acronym': 'fvd'}),
            ('Duel Decks: Venser vs. Koth', u'http://magiccards.info/ddi/en.html', {'acronym': 'ddi'}),
            ('Duel Decks: Ajani vs. Nicol Bolas', u'http://magiccards.info/ddh/en.html', {'acronym': 'ddh'}),
            ('Duel Decks: Knights vs. Dragons', u'http://magiccards.info/ddg/en.html', {'acronym': 'ddg'}),
            ('Duel Decks: Elspeth vs. Tezzeret', u'http://magiccards.info/ddf/en.html', {'acronym': 'ddf'}),
            ('Duel Decks: Phyrexia vs. The Coalition', u'http://magiccards.info/pvc/en.html', {'acronym': 'pvc'}),
            ('Duel Decks: Garruk vs. Liliana', u'http://magiccards.info/gvl/en.html', {'acronym': 'gvl'}),
            ('Duel Decks: Divine vs. Demonic', u'http://magiccards.info/dvd/en.html', {'acronym': 'dvd'}),
            ('Duel Decks: Jace vs. Chandra', u'http://magiccards.info/jvc/en.html', {'acronym': 'jvc'}),
            ('Duel Decks: Elves vs. Goblins', u'http://magiccards.info/evg/en.html', {'acronym': 'evg'}),
            ('Coldsnap Theme Decks', u'http://magiccards.info/cstd/en.html', {'acronym': 'cstd'}),
            ('Ninth Edition Box Set', u'http://magiccards.info/9eb/en.html', {'acronym': '9eb'}),
            ('Eighth Edition Box Set', u'http://magiccards.info/8eb/en.html', {'acronym': '8eb'}),
            ('Deckmasters', u'http://magiccards.info/dm/en.html', {'acronym': 'dm'}),
            ('Beatdown Box Set', u'http://magiccards.info/bd/en.html', {'acronym': 'bd'}),
            ('Battle Royale Box Set', u'http://magiccards.info/br/en.html', {'acronym': 'br'}),
            ('Anthologies', u'http://magiccards.info/at/en.html', {'acronym': 'at'}),
            ('Multiverse Gift Box Cards', u'http://magiccards.info/mgbc/en.html', {'acronym': 'mgbc'}),
            ('Unhinged', u'http://magiccards.info/uh/en.html', {'acronym': 'uh'}),
            ('Unglued', u'http://magiccards.info/ug/en.html', {'acronym': 'ug'}),
            ('Unhinged Alternate Foils', u'http://magiccards.info/uhaa/en.html', {'acronym': 'uhaa'}),
            ('Starter 2000', u'http://magiccards.info/st2k/en.html', {'acronym': 'st2k'}),
            ('Starter 1999', u'http://magiccards.info/st/en.html', {'acronym': 'st'}),
            ('Portal Three Kingdoms', u'http://magiccards.info/p3k/en.html', {'acronym': 'p3k'}),
            ('Portal Second Age', u'http://magiccards.info/po2/en.html', {'acronym': 'po2'}),
            ('Portal', u'http://magiccards.info/po/en.html', {'acronym': 'po'}),
            ('Introductory Two-Player Set', u'http://magiccards.info/itp/en.html', {'acronym': 'itp'}),
            ("Collector's Edition", u'http://magiccards.info/ced/en.html', {'acronym': 'ced'}),
            ("International Collectors' Edition", u'http://magiccards.info/cedi/en.html', {'acronym': 'cedi'}),
            ('15th Anniversary', u'http://magiccards.info/15ann/en.html', {'acronym': '15ann'}),
            ('Grand Prix', u'http://magiccards.info/gpx/en.html', {'acronym': 'gpx'}),
            ('Pro Tour', u'http://magiccards.info/pro/en.html', {'acronym': 'pro'}),
            ('Magic Game Day Cards', u'http://magiccards.info/mgdc/en.html', {'acronym': 'mgdc'}),
            ('Worlds', u'http://magiccards.info/wrl/en.html', {'acronym': 'wrl'}),
            ('Dragon Con', u'http://magiccards.info/drc/en.html', {'acronym': 'drc'}),
            ('Prerelease Events', u'http://magiccards.info/ptc/en.html', {'acronym': 'ptc'}),
            ('Release Events', u'http://magiccards.info/rep/en.html', {'acronym': 'rep'}),
            ('Magic: The Gathering Launch Parties', u'http://magiccards.info/mlp/en.html', {'acronym': 'mlp'}),
            ('Summer of Magic', u'http://magiccards.info/sum/en.html', {'acronym': 'sum'}),
            ('WPN/Gateway', u'http://magiccards.info/grc/en.html', {'acronym': 'grc'}),
            ('Champs', u'http://magiccards.info/cp/en.html', {'acronym': 'cp'}),
            ('Two-Headed Giant Tournament', u'http://magiccards.info/thgt/en.html', {'acronym': 'thgt'}),
            ('Arena League', u'http://magiccards.info/arena/en.html', {'acronym': 'arena'}),
            ('Friday Night Magic', u'http://magiccards.info/fnmp/en.html', {'acronym': 'fnmp'}),
            ('Magic Player Rewards', u'http://magiccards.info/mprp/en.html', {'acronym': 'mprp'}),
            ('Super Series', u'http://magiccards.info/sus/en.html', {'acronym': 'sus'}),
            ('Happy Holidays', u'http://magiccards.info/hho/en.html', {'acronym': 'hho'}),
            ('Judge Gift Program', u'http://magiccards.info/jr/en.html', {'acronym': 'jr'}),
            ('Portal Demogame', u'http://magiccards.info/pot/en.html', {'acronym': 'pot'}),
            ('European Land Program', u'http://magiccards.info/euro/en.html', {'acronym': 'euro'}),
            ('Guru', u'http://magiccards.info/guru/en.html', {'acronym': 'guru'}),
            ('Asia Pacific Land Program', u'http://magiccards.info/apac/en.html', {'acronym': 'apac'}),
            ('WotC Online Store', u'http://magiccards.info/wotc/en.html', {'acronym': 'wotc'}),
            ('Celebration Cards', u'http://magiccards.info/uqc/en.html', {'acronym': 'uqc'}),
            ('Media Inserts', u'http://magiccards.info/mbp/en.html', {'acronym': 'mbp'}),
            ('Legend Membership', u'http://magiccards.info/dcilm/en.html', {'acronym': 'dcilm'}),
        ])
